// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUpI0iFJmarItK9j1OaPyv0BQ8zn6ar4A',
    appId: '1:798597034919:web:f9ab2d9dc860d775593c82',
    messagingSenderId: '798597034919',
    projectId: 'smart-traffic-light-a6297',
    authDomain: 'smart-traffic-light-a6297.firebaseapp.com',
    databaseURL: 'https://smart-traffic-light-a6297-default-rtdb.firebaseio.com',
    storageBucket: 'smart-traffic-light-a6297.firebasestorage.app',
    measurementId: 'G-VKJDN88114',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFySsLQOVwrbeErfjetWgD9dJi-p0VbHM',
    appId: '1:798597034919:android:0c67d884fc4623fe593c82',
    messagingSenderId: '798597034919',
    projectId: 'smart-traffic-light-a6297',
    databaseURL: 'https://smart-traffic-light-a6297-default-rtdb.firebaseio.com',
    storageBucket: 'smart-traffic-light-a6297.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiQjieQBlYw0YUmImvcLWq_2-dKXQgmpM',
    appId: '1:798597034919:ios:2d446461f389f1a4593c82',
    messagingSenderId: '798597034919',
    projectId: 'smart-traffic-light-a6297',
    databaseURL: 'https://smart-traffic-light-a6297-default-rtdb.firebaseio.com',
    storageBucket: 'smart-traffic-light-a6297.firebasestorage.app',
    iosBundleId: 'com.example.traffic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiQjieQBlYw0YUmImvcLWq_2-dKXQgmpM',
    appId: '1:798597034919:ios:2d446461f389f1a4593c82',
    messagingSenderId: '798597034919',
    projectId: 'smart-traffic-light-a6297',
    databaseURL: 'https://smart-traffic-light-a6297-default-rtdb.firebaseio.com',
    storageBucket: 'smart-traffic-light-a6297.firebasestorage.app',
    iosBundleId: 'com.example.traffic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUpI0iFJmarItK9j1OaPyv0BQ8zn6ar4A',
    appId: '1:798597034919:web:e0828baef475c223593c82',
    messagingSenderId: '798597034919',
    projectId: 'smart-traffic-light-a6297',
    authDomain: 'smart-traffic-light-a6297.firebaseapp.com',
    databaseURL: 'https://smart-traffic-light-a6297-default-rtdb.firebaseio.com',
    storageBucket: 'smart-traffic-light-a6297.firebasestorage.app',
    measurementId: 'G-X31EZMZKY7',
  );
}
